apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: infra
spec:
  k0s:
    config:
      spec:
        extensions:
          helm:
            repositories:
            - name: fluxcd-community
              url: https://fluxcd-community.github.io/helm-charts
            charts:
            - name: flux2
              chartname: fluxcd-community/flux2
              order: 1
              version: "2.12.4"
              namespace: flux-system
