# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admins
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
