# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openebs
spec:
  targetNamespace: openebs-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: openebs
      version: 4.0.*
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 10m0s
  values:
    engines:
      replicated:
        mayastor:
          enabled: false
