apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
spec:
  targetNamespace: traefik-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: traefik
      version: 20.5.*
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 10m0s
  values:
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
