apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vault
spec:
  targetNamespace: vault
  install:
    createNamespace: true
  chart:
    spec:
      chart: vault
      version: "v0.27.*"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  interval: 10m
  values:
    server:
      ingress:
        enabled: true
        hosts:
        - host: vault.ajphome.com
